spring.application.name=MusicBoxd

# neutral postgresql connection set up so you don't have to hard code your username/pass as i was having errors with this - AK
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/MusicBoxd_Test}
spring.datasource.username=${DB_USERNAME:${user.name}}
spring.datasource.password=${DB_PASSWORD:}
spring.flyway.locations=classpath:db/migration,classpath:db/test-migration
lastfm.api.key=90689ae0ad8b8d8a25ce581a00907867
spotify.client.id=eab4cf439ed14714b5e7b4735d91515e
spotify.client.secret=a7d1fc0b18354dcaa22db1be602baf7f
spotify.redirect.uri=http://127.0.0.1:8080/spotify/callback
