#SPRING BOOT
spring.application.name=MusicBoxd
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/MusicBoxd_Test}
spring.datasource.username=${TEST_DB_USERNAME}
spring.datasource.password=${TEST_DB_PASSWORD}
spring.flyway.locations=classpath:db/migration,classpath:db/test-migration

#API KEYS
lastfm.api.key=${LASTFM_API_KEY}
spotify.client.id=${SPOTIFY_CLIENT_ID}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET}
spotify.redirect.uri=${SPOTIFY_REDIRECT_URI:http://127.0.0.1:8080/spotify/callback}
ticketmaster.api.key=${TICKETMASTER_API_KEY}
ticketmaster.api.base-url=${TICKETMASTER_API_BASE_URL:https://app.ticketmaster.com/discovery/v2}

#AUTH0
okta.oauth2.issuer=${AUTH0_ISSUER}
okta.oauth2.client-id=${AUTH0_CLIENT_ID}
okta.oauth2.client-secret=${AUTH0_CLIENT_SECRET}