#SPRING BOOT
spring.application.name=MusicBoxd
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/MusicBoxd_Test}
spring.datasource.username=${DB_USERNAME:${user.name}}
spring.datasource.password=${DB_PASSWORD:}
spring.flyway.locations=classpath:db/migration,classpath:db/test-migration

#API KEYS
lastfm.api.key=90689ae0ad8b8d8a25ce581a00907867
spotify.client.id=eab4cf439ed14714b5e7b4735d91515e
spotify.client.secret=a7d1fc0b18354dcaa22db1be602baf7f
spotify.redirect.uri=http://127.0.0.1:8080/spotify/callback
ticketmaster.api.key=8cVErKyWL3GxMYNgDfacWTWGCXEAHQfG
ticketmaster.api.base-url=https://app.ticketmaster.com/discovery/v2
