spring.datasource.url=jdbc:postgresql://localhost:5432/MusicBoxd_Test
spring.datasource.username=
spring.datasource.password=

export LASTFM_API_KEY="90689ae0ad8b8d8a25ce581a00907867"
spotify.client.id=eab4cf439ed14714b5e7b4735d91515e
spotify.client.secret=a7d1fc0b18354dcaa22db1be602baf7f
spotify.redirect.uri=http://127.0.0.1:8080/spotify/callback