server.port=${PORT}
server.address=0.0.0.0
server.forward-headers-strategy=framework 
# for auth0 and gcp to work

spring.datasource.url=jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.enabled=true